version: '3.5'

services:
  essay-backend:
    image: website-backend
    container_name: website-backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENVIRONMENT=dev
    volumes:
      - './website-backend/app:/app'