version: '3.5'

services:
  essay-backend:
    image: website-backend
    container_name: website-backend
    ports:
      - "80:80"
    environment:
      - APP_ENVIRONMENT=dev
    volumes:
      - './website-backend/app:/app'
    command: ["/start-reload.sh"]